package com.m4trust.coreapi.contractintelligence;
import java.net.URI; import java.time.*; import java.util.*;
import tools.jackson.databind.ObjectMapper;
import com.m4trust.coreapi.audit.*; import com.m4trust.coreapi.deal.*; import com.m4trust.coreapi.document.*; import com.m4trust.coreapi.idempotency.*; import com.m4trust.coreapi.integration.messaging.TransactionalOutbox; import com.m4trust.coreapi.organization.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.support.TransactionTemplate;
@Service class AnalysisService implements DealAnalysisProjectionPort {
 private final AnalysisRepository jobs; private final DealAnalysisMutationPort deals; private final DocumentAnalysisInputPort documents; private final DocumentObjectStorage storage; private final IdempotencyService idem; private final TransactionTemplate tx; private final TransactionalOutbox outbox; private final AuditAppendPort audit; private final Clock clock; private final ObjectMapper json;
 AnalysisService(AnalysisRepository jobs,DealAnalysisMutationPort deals,DocumentAnalysisInputPort documents,DocumentObjectStorage storage,IdempotencyService idem,TransactionTemplate tx,TransactionalOutbox outbox,AuditAppendPort audit,Clock clock,ObjectMapper json){this.jobs=jobs;this.deals=deals;this.documents=documents;this.storage=storage;this.idem=idem;this.tx=tx;this.outbox=outbox;this.audit=audit;this.clock=clock;this.json=json;}
 public DealDocumentAnalysis get(OperationContext c,UUID dealId){ require(c,RequestedOperation.DEAL_DOCUMENT_ANALYSIS_READ); DealAnalysisMutationPort.AnalysisTarget t=required(tx.execute(s->deals.lockForAnalysis(c,dealId).orElseThrow(AnalysisExceptions.NotFound::new))); return projection(t.currentDocumentId()); }
 DealDocumentAnalysis request(OperationContext c,UUID dealId,UUID key,UUID correlation){require(c,RequestedOperation.DEAL_DOCUMENT_ANALYSIS_REQUEST); IdempotencyRequest request=new IdempotencyRequest(c.authenticatedUserId(),c.tenantId(),"DEAL_DOCUMENT_ANALYSIS_REQUEST",key,hash(c.activeLegalEntityId(),dealId)); IdempotencyResultReference completed=idem.findCompleted(request).orElse(null); if(completed!=null)return projectionForJob(completed.id());
  DealAnalysisMutationPort.AnalysisTarget pre=required(tx.execute(s->deals.lockForAnalysis(c,dealId).orElseThrow(AnalysisExceptions.NotFound::new))); requireTarget(pre); DocumentAnalysisInputPort.Input input=documents.findAvailable(pre.currentDocumentId()).orElseThrow(()->new AnalysisExceptions.Conflict("DEAL_DOCUMENT_ANALYSIS_DOCUMENT_NOT_AVAILABLE")); DocumentObjectStorage.DirectDownload signed=storage.createDirectDownload(input.objectKey(),input.objectVersion());
  return required(tx.execute(s->{IdempotencyClaim claim=idem.claim(request);if(claim.isReplay())return projectionForJob(claim.resultReference().id()); DealAnalysisMutationPort.AnalysisTarget target=deals.lockForAnalysis(c,dealId).orElseThrow(AnalysisExceptions.NotFound::new);requireTarget(target); DocumentAnalysisInputPort.Input locked=documents.findAvailable(target.currentDocumentId()).orElseThrow(()->new AnalysisExceptions.Conflict("DEAL_DOCUMENT_ANALYSIS_DOCUMENT_NOT_AVAILABLE")); if(!locked.id().equals(input.id())||!locked.objectVersion().equals(input.objectVersion()))throw new AnalysisExceptions.Conflict("DEAL_DOCUMENT_ANALYSIS_DOCUMENT_NOT_AVAILABLE");if(jobs.active(locked.id()))throw new AnalysisExceptions.Conflict("DEAL_DOCUMENT_ANALYSIS_ACTIVE_JOB_EXISTS"); Instant now=clock.instant(); UUID jobId=UUID.randomUUID(); jobs.insert(new AnalysisRepository.Row(jobId,target.tenantId(),target.dealId(),locked.id(),locked.objectVersion(),locked.sha256(),"QUEUED",now,null,null,null,null,null,0)); outbox.enqueue("ai.document-extraction.requested.v1","m4trust.ai.commands","ai.document-extraction.requested.v1",event(jobId,target,locked,key,correlation,signed,now)); audit.append(new AuditRecord(UUID.randomUUID(),target.tenantId(),c.authenticatedUserId(),c.activeLegalEntityId(),"ANALYSIS_JOB",jobId,"DOCUMENT_ANALYSIS_REQUESTED",correlation,null,now)); idem.recordResult(claim,new IdempotencyResultReference("DEAL_DOCUMENT_ANALYSIS",jobId));return projection(locked.id());})); }
 private String event(UUID job,DealAnalysisMutationPort.AnalysisTarget t,DocumentAnalysisInputPort.Input d,UUID key,UUID correlation,DocumentObjectStorage.DirectDownload link,Instant now){try{Map<String,Object> envelope=new LinkedHashMap<>(); envelope.put("eventId",UUID.randomUUID());envelope.put("eventType","ai.job.requested.v1");envelope.put("schemaVersion","1.0.0");envelope.put("occurredAt",now);envelope.put("correlationId",correlation);envelope.put("causationId",null);envelope.put("jobId",job);envelope.put("jobType","DOCUMENT_EXTRACTION");envelope.put("tenantId",t.tenantId());envelope.put("transactionId",t.dealId());envelope.put("subjectId",d.id());envelope.put("idempotencyKey",key.toString());envelope.put("producer",Map.of("service","core-api","version","0.1.0"));envelope.put("payload",Map.of("input",Map.of("documentId",d.id(),"fileName",d.fileName(),"mediaType",d.mediaType(),"sizeBytes",d.sizeBytes(),"sha256",d.sha256(),"download",Map.of("url",link.url().toString(),"expiresAt",link.expiresAt())),"processing",Map.of("languageHints",List.of(),"documentCategory","B2B_CONTRACT","requestedOutputSchema","m4trust.document-extraction-result","requestedOutputSchemaVersion","1.0.0","privacyProfile","DEFAULT","retrievalProfile","M4TRUST_LEGAL_DEFAULT"),"deadlineAt",link.expiresAt()));return json.writeValueAsString(envelope);}catch(Exception e){throw new IllegalStateException(e);}}
 private DealDocumentAnalysis projection(UUID doc){return jobs.latest(doc).map(this::row).orElse(new DealDocumentAnalysis(doc,"NOT_REQUESTED",null,null,null,null,null,null));} private DealDocumentAnalysis projectionForJob(UUID id){return jobs.latestForJob(id).map(this::row).orElseThrow(()->new AnalysisExceptions.Conflict("DEAL_DOCUMENT_ANALYSIS_DOCUMENT_NOT_AVAILABLE"));} private DealDocumentAnalysis row(AnalysisRepository.Row r){return new DealDocumentAnalysis(r.documentId(),r.status(),r.requestedAt(),r.processingStartedAt(),r.completedAt(),r.failedAt(),r.failureCode()==null?null:new DealDocumentAnalysis.Failure(r.failureCode(),Boolean.TRUE.equals(r.retryRecommended())),null);} public AnalysisSummary summary(UUID d){DealDocumentAnalysis p=projection(d);return new AnalysisSummary(p.currentDocumentId(),p.status(),p.requestedAt(),p.processingStartedAt(),p.completedAt(),p.failedAt(),p.failure()==null?null:new Failure(p.failure().code(),p.failure().retryRecommended()));} public boolean hasActiveJob(UUID d){return jobs.active(d);} private void requireTarget(DealAnalysisMutationPort.AnalysisTarget t){if(!t.initiator())throw new AnalysisExceptions.Forbidden();if(!t.acceptsAnalysis())throw new AnalysisExceptions.Conflict("DEAL_STATE_CONFLICT");if(t.currentDocumentId()==null)throw new AnalysisExceptions.Conflict("DEAL_DOCUMENT_ANALYSIS_DOCUMENT_NOT_AVAILABLE");} private void require(OperationContext c,RequestedOperation o){if(c.requestedOperation()!=o)throw new IllegalArgumentException();} private String hash(UUID a,UUID d){return a+":"+d;} private static <T>T required(T x){if(x==null)throw new IllegalStateException();return x;}
}
