package com.m4trust.coreapi.contractintelligence;

import com.m4trust.coreapi.audit.*;
import com.m4trust.coreapi.deal.*;
import com.m4trust.coreapi.idempotency.*;
import com.m4trust.coreapi.organization.*;
import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.*;
import tools.jackson.databind.node.*;

@Service
class ReviewService {
  private final AnalysisRepository analyses; private final RuleSetRepository rules; private final DealAnalysisReadPort reads; private final DealAnalysisMutationPort mutations; private final IdempotencyService idempotency; private final AuditAppendPort audit; private final TransactionTemplate tx; private final Clock clock; private final ObjectMapper json;
  ReviewService(AnalysisRepository analyses,RuleSetRepository rules,DealAnalysisReadPort reads,DealAnalysisMutationPort mutations,IdempotencyService idempotency,AuditAppendPort audit,TransactionTemplate tx,Clock clock,ObjectMapper json){this.analyses=analyses;this.rules=rules;this.reads=reads;this.mutations=mutations;this.idempotency=idempotency;this.audit=audit;this.tx=tx;this.clock=clock;this.json=json;}
  Object review(OperationContext c,UUID deal){ require(c,RequestedOperation.DEAL_EXTRACTION_REVIEW_READ); var v=reads.findAnalysisVisibility(c,deal).orElseThrow(AnalysisExceptions.DealNotFound::new); var job=analyses.findLatestForDocument(v.currentDocumentId()).filter(j->j.status()==AnalysisJobStatus.REVIEW_REQUIRED).orElseThrow(()->new AnalysisExceptions.Conflict("DEAL_STATE_CONFLICT")); return Map.of("analysisId",job.id(),"documentId",job.documentId(),"rules",resultRules(job.id())); }
  Object accept(OperationContext c,UUID deal,UUID key,UUID correlation,JsonNode request){ require(c,RequestedOperation.DEAL_EXTRACTION_REVIEW_ACCEPT); UUID analysisId=uuid(request,"analysisId"); long expected=number(request,"expectedVersion"); String hash=Integer.toHexString(request.toString().hashCode()); var ir=new IdempotencyRequest(c.authenticatedUserId(),c.tenantId(),"DEAL_EXTRACTION_REVIEW_ACCEPT",key,hash); var completed=idempotency.findCompleted(ir).orElse(null); if(completed!=null)return version(deal,completed.id()); return tx.execute(s->acceptLocked(c,deal,correlation,request,ir,analysisId,expected)); }
  Object history(OperationContext c,UUID deal){ require(c,RequestedOperation.DEAL_RULE_SET_VERSION_READ); visible(c,deal); return Map.of("items",rules.list(deal).stream().map(this::summary).toList()); }
  Object version(OperationContext c,UUID deal,UUID id){ require(c,RequestedOperation.DEAL_RULE_SET_VERSION_READ); visible(c,deal); return version(deal,id); }
  private Object acceptLocked(OperationContext c,UUID deal,UUID correlation,JsonNode req,IdempotencyRequest ir,UUID analysisId,long expected){ var claim=idempotency.claim(ir); if(claim.isReplay())return version(deal,claim.resultReference().id()); var target=mutations.lockForReview(c,deal).orElseThrow(AnalysisExceptions.DealNotFound::new); if(!target.initiator())throw new AnalysisExceptions.RequestForbidden(); if(target.version()!=expected)throw new AnalysisExceptions.Conflict("DEAL_STALE_VERSION"); var job=analyses.findByIdForUpdate(analysisId).filter(j->j.dealId().equals(deal)&&j.documentId().equals(target.currentDocumentId())&&j.status()==AnalysisJobStatus.REVIEW_REQUIRED).orElseThrow(()->new AnalysisExceptions.Conflict("DEAL_STATE_CONFLICT")); UUID extraction=analyses.findResultId(job.id()).orElseThrow(()->new AnalysisExceptions.Conflict("DEAL_STATE_CONFLICT")); ArrayNode extracted=resultRules(job.id()); DecisionOutput out=decide(extracted,req.get("decisions")); UUID id=UUID.randomUUID(); Instant now=clock.instant(); var previous=rules.latest(deal).orElse(null); rules.insert(id,deal,previous==null?1:previous.version()+1,job.id(),extraction,c.authenticatedUserId(),now,previous==null?null:previous.id(),out.rules().toString(),out.excluded().toString()); analyses.accept(job); mutations.setCurrentRuleSet(deal,id,now); audit.append(new AuditRecord(UUID.randomUUID(),target.owningTenantId(),c.authenticatedUserId(),c.activeLegalEntityId(),"RULE_SET_VERSION",id,"EXTRACTION_REVIEW_ACCEPTED",correlation,null,now)); idempotency.recordResult(claim,new IdempotencyResultReference("RULE_SET_VERSION",id)); return version(deal,id); }
  private DecisionOutput decide(ArrayNode extracted,JsonNode decisions){ if(decisions==null||!decisions.isArray())throw new AnalysisExceptions.MalformedRequest(); Map<String,JsonNode> byRef=new HashMap<>(); for(JsonNode d:decisions){String ref=d.path("ruleReference").asText();if(!ref.isBlank()&&byRef.put(ref,d)!=null)throw new AnalysisExceptions.MalformedRequest();} ArrayNode finalRules=json.createArrayNode(), excluded=json.createArrayNode(); int manual=1; for(JsonNode original:extracted){String ref=original.path("ruleReference").asText();JsonNode d=byRef.remove(ref);if(d==null)throw new AnalysisExceptions.MalformedRequest();String kind=d.path("decision").asText();if("EXCLUDED".equals(kind)){excluded.add(ref);continue;} ObjectNode value=("MODIFIED".equals(kind)?(ObjectNode)d.deepCopy():(ObjectNode)original.deepCopy()); value.put("ruleReference",ref); value.put("decision",kind); value.set("legalBasis",original.get("legalBasis")); value.put("legalBasisProvenance","MODIFIED".equals(kind)?"REVIEWER_MODIFIED":"EXTRACTED"); finalRules.add(value);} for(JsonNode d:byRef.values()){if(!"ADDED".equals(d.path("decision").asText()))throw new AnalysisExceptions.MalformedRequest();ObjectNode value=(ObjectNode)d.deepCopy();value.put("ruleReference","manual-"+manual++);value.put("legalBasis",(String)null);value.put("legalBasisProvenance","MANUALLY_ADDED");finalRules.add(value);} return new DecisionOutput(finalRules,excluded); }
  private ArrayNode resultRules(UUID job){try{JsonNode n=json.readTree(analyses.findResult(job).orElseThrow(()->new AnalysisExceptions.Conflict("DEAL_STATE_CONFLICT")));return (ArrayNode)n.path("rules");}catch(Exception e){throw new IllegalStateException(e);}}
  private Object version(UUID deal,UUID id){var r=rules.find(deal,id).orElseThrow(AnalysisExceptions.DealNotFound::new);try{return full(r);}catch(Exception e){throw new IllegalStateException(e);}}
  private Object full(RuleSetRepository.Row r)throws Exception{Map<String,Object> m=base(r);JsonNode rulesNode=json.readTree(r.rules());m.put("ruleCount",rulesNode.size());m.put("rules",rulesNode);m.put("excludedRuleReferences",json.readTree(r.excluded()));return m;}
  private Object summary(RuleSetRepository.Row r){try{Map<String,Object> m=base(r);m.put("ruleCount",json.readTree(r.rules()).size());return m;}catch(Exception e){throw new IllegalStateException(e);}}
  private static Map<String,Object> base(RuleSetRepository.Row r){Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.id());m.put("version",r.version());m.put("sourceAnalysisId",r.analysisId());m.put("sourceExtractionResultVersionId",r.extractionId());m.put("createdAt",r.createdAt());m.put("createdByUserId",r.createdBy());m.put("previousRuleSetVersionId",r.previousId());return m;}
  private void visible(OperationContext c,UUID d){if(reads.findAnalysisVisibility(c,d).isEmpty())throw new AnalysisExceptions.DealNotFound();} private static UUID uuid(JsonNode n,String f){try{return UUID.fromString(n.path(f).asText());}catch(Exception e){throw new AnalysisExceptions.MalformedRequest();}} private static long number(JsonNode n,String f){if(!n.has(f)||!n.get(f).canConvertToLong()||n.get(f).asLong()<0)throw new AnalysisExceptions.MalformedRequest();return n.get(f).asLong();} private static void require(OperationContext c,RequestedOperation o){if(c.requestedOperation()!=o)throw new IllegalArgumentException("wrong operation");} record DecisionOutput(ArrayNode rules,ArrayNode excluded){}
}
