package com.m4trust.coreapi.fulfillment.domain;

/** Stable fulfillment conflict identifiers, mapped to public API codes at the boundary. */
public enum FulfillmentErrorCode {
  DEAL_STATE_CONFLICT,
  DEAL_STALE_VERSION,
  EVIDENCE_MILESTONE_CONFLICT,
  EVIDENCE_STATE_CONFLICT,
  EVIDENCE_UPLOAD_EXPIRED,
  EVIDENCE_UPLOAD_STATE_CONFLICT,
  EVIDENCE_VERIFICATION_FAILED,
  FULFILLMENT_ALREADY_EXISTS,
  FULFILLMENT_COMPLETED,
  FULFILLMENT_EVIDENCE_POLICY_CONFLICT,
  FULFILLMENT_EVIDENCE_PRESENT,
  FULFILLMENT_STALE_VERSION,
  FULFILLMENT_STATE_CONFLICT,
  EVIDENCE_ALREADY_SUBMITTED,
  VIDEO_ANALYSIS_ACTIVE_JOB_EXISTS,
  VIDEO_ANALYSIS_ALREADY_COMPLETED,
  VIDEO_ANALYSIS_EVIDENCE_NOT_ELIGIBLE,
  EVIDENCE_STALE_VERSION
}
