package com.m4trust.coreapi.organization;

public enum RequestedOperation {
    LEGAL_ENTITY_DETAIL_READ,
    LEGAL_ENTITY_MEMBERS_READ,
    DEAL_CREATE,
    DEAL_LIST_READ,
    DEAL_DETAIL_READ,
    DEAL_UPDATE,
    DEAL_PARTIES_UPDATE,
    DEAL_CANCEL,
    DEAL_INVITATION_CREATE,
    DEAL_INVITATION_LIST_READ,
    DEAL_INVITATION_REVOKE,
    DEAL_DOCUMENT_UPLOAD_INTENT_CREATE,
    DOCUMENT_UPLOAD_FINALIZE,
    DEAL_DOCUMENT_LIST_READ,
    DOCUMENT_DOWNLOAD_LINK_CREATE
}
